#!/bin/bash
set -e

gcc -g -m32 -c valid/util.s
gcc -g -m32 -c valid/daemon.s
gcc -g -m32 -c valid/cache.s
gcc -g -m32 -c valid/assoc.s
gcc -g -m32 -c valid/stats.s
gcc -g -m32 -c valid/hash.s

gcc -g -m32 -c valid/items.c

gcc -g -m32 -c valid/thread.c
gcc -g -m32 -c valid/slabs.c
gcc -g -m32 -c valid/memcached-shunting.c

gcc -g -m32 assoc.o cache.o daemon.o hash.o items.o memcached-shunting.o thread.o slabs.o stats.o util.o -levent -lpthread
# gcc -g -m32 -c stage/assoc.c
# ../../scc -DHAVE_CONFIG_H ../memcached-1.4.17/assoc.c > stage/assoc.s || true
# gcc -m32 -c -g -DHAVE_CONFIG_H ../memcached-1.4.17/assoc-shunting.c -o assoc.o
